name: Render Template
description: Renders file based on template and passed variables
runs:
  using: docker
  image: Dockerfile

inputs:
  template:
    description: Path to template
    required: false
    default: .kube.yml

  vars:
    description: Variables to use in template
    required: false

outputs:
  result:
    description: Rendered file content
