name: Render Template
description: Renders file based on template and passed variables

author: Konstantin Chukhlomin <mail@chuhlomin.com>

branding:
  icon: file-text
  color: purple

runs:
  using: docker
  image: Dockerfile

inputs:
  template:
    description: Path to template
    required: true

  vars:
    description: Variables to use in template
    required: false

outputs:
  result:
    description: Rendered file content
